// @ts-nocheck
import { useEffect, useState, FC } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import styles from "../../styles/loading.module.css";
import { useCountUp } from "use-count-up";

const LoadingPage = (props: {randomAmountGacha: any, setFinishedLoadingAnim: any, setHaveGambled: any}) => {
    const [isTransferLoading, setIsTransferLoading] = useState(false);
    const [endAmount, setEndAmount] = useState(0);
    const [startAmount, setStartAmount] = useState(-875.039);

    const [animationEnded, setAnimationEnded] = useState(false);
    const [animationStarted, setAnimationStarted] = useState(false);
    const [animationComplete, setAnimationComplete] = useState(false);
    const [blackoutStart, setBlackoutStart] = useState(false);

    const [start, setStart] = useState(1492);
    const [end, setEnd] = useState(7894);
    const [duration, setDuration] = useState(2);
    const [firstAnimFinished, setFirstAnimFinished] = useState(false);

    const { value, reset } = useCountUp({
        isCounting: true,
        start,
        end,
        duration
    });

    useEffect(() => {
      setEnd(Math.floor(Math.random() * 1000000 + 1))
    }, [])

    useEffect(() => {
      if (animationEnded) {
        setStartAmount(endAmount)
        setEndAmount(props.randomAmountGacha)
      }
    }, [animationEnded])

    useEffect(() => {
        if (value == end && !firstAnimFinished) {
            setFirstAnimFinished(true)
            setTimeout(() => {
                setStart(end)
                setEnd(props.randomAmountGacha)
                reset()
                setAnimationEnded(true)
            }, 500);
        }
        else if (value == end && animationEnded) setAnimationComplete(true)
        if (!animationStarted) setAnimationStarted(true)
    }, [value])
    
    
    // Fade to back then show again
    // function waitAndCloseBlackout() {
    //     setBlackoutStart(true)
    //     // setTimeout(() => {
            
    //     // }, 230);
    //     setTimeout(() => {
    //         setBlackoutStart(false)
    //     }, 3000);
    // }

    return (
        <div className={styles.container}>
            <Head>
                <title>Crypto Gacha</title>
                <meta
                content="Generated by @rainbow-me/create-rainbowkit"
                name="description"
                />
                <link href='/favicon.ico' rel="shortcut icon" />
            </Head>
            
            <main className={blackoutStart ? styles.mainBlack : styles.main}>
                <div style={{display: "flex", justifyContent: "center", flexDirection: "column", width: "100%", alignItems: "center"}}>
                    <div className={animationEnded ? styles.counter : styles.startAnim} style={{display: "flex", justifyContent: "center", flexDirection: "column", width: "100%", alignItems: "center"}}>
                        <p className={animationStarted ? (animationEnded ? styles.textGrowEnd : styles.textGrowStart) : styles.textGrowInitial} style={{fontSize: "12px"}}>
                            {value} GCG
                        </p>
                    </div>
                </div>


                <div>
                    { isTransferLoading &&
                    <div>
                        <p style={{color: "red"}}>La transaction est en cours... veuillez patienter</p>
                    </div>}
                </div>

                {animationEnded && animationComplete &&
                    <div>
                        <h4>Vous avez obtenu : {props.randomAmountGacha}</h4>
                    </div>
                }
                {!blackoutStart && animationEnded &&
                    <button style={{marginTop: "40px"}} onClick={() => props.setHaveGambled(false)}>Retour</button>
                }
            </main>
        </div>
    );
};
 
export default LoadingPage;