import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
 
import { ethers } from "ethers";
import { ConnectButton } from "@rainbow-me/rainbowkit";
 
import styles from "../../styles/loading.module.css";

const LoadingPage = (props: {randomAmountGacha}) => {
    const [isTransferLoading, setIsTransferLoading] = useState(false);

    return (
        <div className={styles.container}>
            <Head>
                <title>Crypto Gacha</title>
                <meta
                content="Generated by @rainbow-me/create-rainbowkit"
                name="description"
                />
                <link href='/favicon.ico' rel="shortcut icon" />
            </Head>
            
            <main className={styles.main}>
                <div style={{display: "flex", justifyContent: "center", flexDirection: "column", width: "100%", /* backgroundColor: "red", */ alignItems: "center"}}>

                    <div style={{display: "flex", justifyContent: "center", flexDirection: "column", width: "100%", /* backgroundColor: "red", */ alignItems: "center"}}>
                        
                    </div>
                </div>


                <div>
                    <p>{props.randomAmountGacha}</p>

                    { isTransferLoading &&
                    <div>
                        <p style={{color: "red"}}>La transaction est en cours... veuillez patienter</p>
                    </div>}
                </div>

                {!isTransferLoading &&
                    <div>
                        <h4>Vous avez gagné : {props.randomAmountGacha}</h4>
                    </div>
                }
            </main>
        </div>
    );
};
 
export default LoadingPage;